service: node-restful-api

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  profile: afreeca
  region: eu-west-2

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "lambda:*"
      Resource:
        - "*"

functions:
  create:
    handler: user/create.create
    events:
      - http:
          path: user
          method: post
          # cors: true # just on development, not needed in production

  delete:
    handler: user/delete.delete
    events: #event(http) on the specified path and method - for api gateway
      - http:
          path: user/{id}
          method: delete
          # cors: true

  retrieve:
    handler: user/retrieve.retrieve
    events:
      - http:
          path: user/{id}
          method: get
          # cors: true
